url: "https://emuurom.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "EMUUROM" # the name of your site, e.g. ACME Corp.
description: "The nonviolent creature-scanning metroidvania"
twitter_username: borbware
github_username:  borbware
theme: minima
plugins:
  - jekyll-feed
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
  math_engine: mathjax
  syntax_highlighter: rouge